/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bd8c339b-e0cc-4aec-b225-7fb70f0906b2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8nJHZgffZ",
    "aws_user_pools_web_client_id": "730i71nr6ft6shdnm96f4uqbup",
    "oauth": {}
};


export default awsmobile;
